name: CI/CD Workflow

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0, v1.0.1)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Replace with your build command

      - name: Deploy
        run: npm run deploy  # Replace with your deploy command

  create_release:
    runs-on: ubuntu-latest
    needs: deploy  # Ensure this job runs after the deploy job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create ZIP archive
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          zip -r "DevOps-Demo-${VERSION}.zip" public/*

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body: ''
          prerelease: ${{ startsWith(github.ref_name, 'beta-') }}
          files: |
            ${{ github.workspace }}/DevOps-Demo-${{ github.ref_name }}.zip
            ${{ github.workspace }}/public/**/*
